[workspace]
members = ["backend"]

resolver = "2"

[profile.release]
opt-level = "z"      # Оптимизация по размеру
lto = true           # Линк-тайм оптимизация (удаляет мертвый код)
codegen-units = 1    # Улучшает оптимизацию компилятора
panic = "abort"      # Убирает тяжелую логику раскрутки стека
strip = true         # Вырезает таблицы символов (сильно уменьшает вес)
